# -*- mode: Python; -*-

## @file client/SConscript
#  @brief scons build for client part (JavaScript, AngularJS)

import os
Import('env')
Import('WEB_SRV_PREFIX WEB_SRV_HOST WEB_SRV_PORT WEB_CLIENT_HOST WEB_CLIENT_PORT')

os.system('gulp build-app-prod')